// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Rose.Network.Packets
{

public enum LoginReplyValue : sbyte
{
  OK = 0,
  NOT_OK = 1,
};


}
