// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Rose.Network.Packets
{

public enum PacketType : byte
{
  NONE = 0,
  CharacterCreateRequest = 1,
  LoginRequest = 2,
  LoginReply = 3,
  UpdateStats = 4,
};


}
